const pool = require('../db/pool');
const { notify } = require('./notify');

// Single source of truth for every plan's limits, features, and price.
// Paystack plan codes come from env vars (created manually in the Paystack
// dashboard -- see .env.example) rather than being generated by the app,
// so there's nothing here that needs a live API call to define.
const PLANS = {
  free: {
    key: 'free', name: 'Free', tagline: 'Try it out',
    seatLimit: 3, boardLimit: 1, attachmentLimitMb: 0,
    hasMap: false, hasExport: false, hasOrgTags: false, hasMultiAdmin: false,
    priceMonthly: 0, priceAnnual: 0,
    paystackPlanCode: { monthly: null, annual: null }
  },
  individual: {
    key: 'individual', name: 'Individual', tagline: 'One person, self-pay',
    seatLimit: 1, boardLimit: null, attachmentLimitMb: 250,
    hasMap: true, hasExport: true, hasOrgTags: false, hasMultiAdmin: false,
    priceMonthly: 5, priceAnnual: 48,
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PLAN_INDIVIDUAL_MONTHLY,
      annual: process.env.PAYSTACK_PLAN_INDIVIDUAL_ANNUAL
    }
  },
  team_starter: {
    key: 'team_starter', name: 'Team Starter', tagline: 'Up to 10 seats',
    seatLimit: 10, boardLimit: null, attachmentLimitMb: 1024 + 10 * 200,
    hasMap: true, hasExport: true, hasOrgTags: true, hasMultiAdmin: false,
    priceMonthly: 15, priceAnnual: 144,
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PLAN_TEAM_STARTER_MONTHLY,
      annual: process.env.PAYSTACK_PLAN_TEAM_STARTER_ANNUAL
    }
  },
  team: {
    key: 'team', name: 'Team', tagline: 'Up to 50 seats',
    seatLimit: 50, boardLimit: null, attachmentLimitMb: 1024 + 50 * 200,
    hasMap: true, hasExport: true, hasOrgTags: true, hasMultiAdmin: false,
    priceMonthly: 48, priceAnnual: 460,
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PLAN_TEAM_MONTHLY,
      annual: process.env.PAYSTACK_PLAN_TEAM_ANNUAL
    }
  },
  team_growth: {
    key: 'team_growth', name: 'Team Growth', tagline: 'Up to 150 seats',
    seatLimit: 150, boardLimit: null, attachmentLimitMb: 1024 + 150 * 500,
    hasMap: true, hasExport: true, hasOrgTags: true, hasMultiAdmin: true,
    priceMonthly: 120, priceAnnual: 1152,
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PLAN_TEAM_GROWTH_MONTHLY,
      annual: process.env.PAYSTACK_PLAN_TEAM_GROWTH_ANNUAL
    }
  },
  team_business: {
    key: 'team_business', name: 'Team Business', tagline: 'Up to 400 seats',
    seatLimit: 400, boardLimit: null, attachmentLimitMb: 1024 + 400 * 500,
    hasMap: true, hasExport: true, hasOrgTags: true, hasMultiAdmin: true,
    priceMonthly: 250, priceAnnual: 2400,
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PLAN_TEAM_BUSINESS_MONTHLY,
      annual: process.env.PAYSTACK_PLAN_TEAM_BUSINESS_ANNUAL
    }
  }
};

const TRIAL_DAYS = Number(process.env.BILLING_TRIAL_DAYS || 14);
// How long before a trial ends to send the one reminder notification.
const TRIAL_REMINDER_DAYS_BEFORE = 3;

const PLAN_ORDER = ['free', 'individual', 'team_starter', 'team', 'team_growth', 'team_business'];

function getPlan(key) {
  return PLANS[key] || PLANS.free;
}

function planList() {
  return PLAN_ORDER.map((k) => PLANS[k]);
}

// How much of an org's limits are currently used. Board/seat counts are
// cheap COUNTs; attachments sum the existing size_bytes column rather than
// reading BYTEA content, so this stays fast even with large files stored.
async function getOrgUsage(orgId) {
  const { rows: boardRows } = await pool.query('SELECT COUNT(*)::int AS count FROM boards WHERE org_id = $1', [orgId]);
  const { rows: seatRows } = await pool.query('SELECT COUNT(*)::int AS count FROM org_members WHERE org_id = $1', [orgId]);
  const { rows: attRows } = await pool.query(
    `SELECT COALESCE(SUM(ca.size_bytes), 0)::bigint AS bytes
     FROM card_attachments ca
     JOIN cards c ON c.id = ca.card_id
     JOIN lists l ON l.id = c.list_id
     JOIN boards b ON b.id = l.board_id
     WHERE b.org_id = $1`,
    [orgId]
  );
  const attachmentBytes = Number(attRows[0].bytes);
  return {
    boards: boardRows[0].count,
    seats: seatRows[0].count,
    attachmentBytes,
    attachmentMb: Math.round((attachmentBytes / (1024 * 1024)) * 10) / 10
  };
}

// Which board IDs are over the org's current board limit and should be
// treated as read-only. Oldest boards (by creation date) stay active;
// the newest ones beyond the limit get locked -- predictable and doesn't
// require picking anything for the admin.
async function getLockedBoardIds(orgId, boardLimit) {
  if (boardLimit === null || boardLimit === undefined) return new Set();
  const { rows } = await pool.query(
    'SELECT id FROM boards WHERE org_id = $1 ORDER BY created_at ASC OFFSET $2',
    [orgId, boardLimit]
  );
  return new Set(rows.map((r) => r.id));
}

async function isBoardLocked(orgId, boardId, boardLimit) {
  if (boardLimit === null || boardLimit === undefined) return false;
  const locked = await getLockedBoardIds(orgId, boardLimit);
  return locked.has(Number(boardId));
}

async function notifyOrgAdmins(orgId, message, link) {
  const { rows } = await pool.query(`SELECT user_id FROM org_members WHERE org_id = $1 AND role = 'admin'`, [orgId]);
  await Promise.all(rows.map((r) => notify(r.user_id, orgId, message, link)));
}

// Applies a successful Paystack charge to an org: activates the plan,
// logs the transaction, and notifies admins. Shared by TWO callers --
// the webhook handler (routes/webhooks.js, the authoritative path) and
// the checkout callback (routes/billing.js#/billing/callback, a
// same-request fallback for cases where the webhook is delayed, not yet
// configured, or silently failing) -- so a working upgrade doesn't
// depend entirely on webhook delivery. Safe to call twice for the same
// reference: the organizations UPDATE just re-sets the same values, and
// the transaction-log/notification step is skipped if that reference was
// already recorded as successful.
async function applyChargeSuccess({ orgId, customerCode, planKey, cycle, reference, amountUsd, rawEvent }) {
  let org;
  if (orgId) {
    const { rows } = await pool.query('SELECT * FROM organizations WHERE id = $1', [orgId]);
    org = rows[0];
  } else if (customerCode) {
    const { rows } = await pool.query('SELECT * FROM organizations WHERE paystack_customer_code = $1', [customerCode]);
    org = rows[0];
  }
  if (!org) {
    console.error('applyChargeSuccess: could not resolve an org for this payment.', { orgId, customerCode, reference });
    return null;
  }

  // If this exact reference is already logged as successful (the other
  // caller got there first), just confirm the org record matches and
  // skip re-notifying -- avoids a duplicate "payment received" ping.
  let alreadyApplied = false;
  if (reference) {
    const { rows } = await pool.query(
      'SELECT status FROM billing_transactions WHERE paystack_reference = $1',
      [reference]
    );
    alreadyApplied = rows[0] && rows[0].status === 'success';
  }

  const isFirstCharge = !org.paystack_customer_code;

  await pool.query(
    `UPDATE organizations
     SET plan_key = COALESCE($2, plan_key),
         billing_cycle = COALESCE($3, billing_cycle),
         subscription_status = 'active',
         paystack_customer_code = COALESCE(paystack_customer_code, $4),
         grace_period_ends_at = NULL,
         trial_ends_at = NULL
     WHERE id = $1`,
    [org.id, planKey || null, cycle || null, customerCode || null]
  );

  if (reference) {
    await pool.query(
      `INSERT INTO billing_transactions (org_id, paystack_reference, plan_key, billing_cycle, type, amount_usd, status, raw_event)
       VALUES ($1,$2,$3,$4,$5,$6,'success',$7)
       ON CONFLICT (paystack_reference) DO UPDATE SET status = 'success', raw_event = EXCLUDED.raw_event`,
      [org.id, reference, planKey || org.plan_key, cycle || org.billing_cycle, isFirstCharge ? 'subscription_start' : 'renewal', amountUsd || null, JSON.stringify(rawEvent || {})]
    );
  }

  if (!alreadyApplied) {
    await notifyOrgAdmins(
      org.id,
      isFirstCharge
        ? `Payment received -- this organization is now on the ${getPlan(planKey || org.plan_key).name} plan.`
        : `Your ${getPlan(org.plan_key).name} subscription renewed successfully.`,
      '/billing'
    );
  }

  return { ...org, plan_key: planKey || org.plan_key, billing_cycle: cycle || org.billing_cycle, subscription_status: 'active' };
}

// Called once per request (from the org-context middleware in server.js)
// with the org row already loaded. If a canceled subscription's paid
// period has ended, or a payment-failure grace period has expired, this
// downgrades the org to Free right here -- no cron job needed, since every
// authenticated page load passes through here anyway. Returns the
// (possibly updated) org fields so the rest of the request uses correct,
// current values instead of a stale plan.
async function syncOrgPlan(org) {
  if (!org || org.plan_key === 'free') return org;
  const now = new Date();

  // Trial reminder: fires once, partway through the trial, via the
  // trial_reminder_sent_at flag so it doesn't re-fire on every request
  // during the reminder window.
  if (org.subscription_status === 'trial' && org.trial_ends_at && !org.trial_reminder_sent_at) {
    const msUntilEnd = new Date(org.trial_ends_at) - now;
    const reminderWindowMs = TRIAL_REMINDER_DAYS_BEFORE * 24 * 60 * 60 * 1000;
    if (msUntilEnd > 0 && msUntilEnd <= reminderWindowMs) {
      await pool.query('UPDATE organizations SET trial_reminder_sent_at = NOW() WHERE id = $1', [org.id]);
      const daysLeft = Math.max(1, Math.ceil(msUntilEnd / (24 * 60 * 60 * 1000)));
      await notifyOrgAdmins(
        org.id,
        `Your ${getPlan(org.plan_key).name} trial ends in ${daysLeft} day${daysLeft === 1 ? '' : 's'}. Subscribe on the Billing page to keep access.`,
        '/billing'
      );
      org = { ...org, trial_reminder_sent_at: now };
    }
  }

  const periodEnded = org.current_period_end && new Date(org.current_period_end) < now;
  const graceEnded = org.grace_period_ends_at && new Date(org.grace_period_ends_at) < now;
  const trialEnded = org.subscription_status === 'trial' && org.trial_ends_at && new Date(org.trial_ends_at) < now;

  const shouldDowngrade =
    (org.subscription_status === 'canceled' && periodEnded) ||
    (org.subscription_status === 'grace' && graceEnded) ||
    trialEnded;

  if (!shouldDowngrade) return org;

  const endedPlan = getPlan(org.plan_key).name;
  await pool.query(
    `UPDATE organizations
     SET plan_key = 'free', billing_cycle = NULL, subscription_status = 'none',
         current_period_end = NULL, grace_period_ends_at = NULL, trial_ends_at = NULL
     WHERE id = $1`,
    [org.id]
  );
  await notifyOrgAdmins(
    org.id,
    trialEnded
      ? `Your ${endedPlan} trial has ended and this organization has moved to the Free plan. Subscribe on the Billing page to get it back.`
      : 'Your subscription has ended and this organization has moved to the Free plan. Boards and members beyond the Free plan\'s limits are now read-only until you upgrade.',
    '/billing'
  );
  return {
    ...org,
    plan_key: 'free',
    billing_cycle: null,
    subscription_status: 'none',
    current_period_end: null,
    grace_period_ends_at: null,
    trial_ends_at: null
  };
}

// Starts a free trial on a paid plan -- no payment/card required. One
// trial per org, ever (has_used_trial), so this can't be used to cycle
// through every tier for indefinite free access. The trial silently
// converts to Free (not an automatic charge) when it ends -- see
// syncOrgPlan above -- since there's no stored payment authorization to
// charge without the admin actively checking out.
async function startTrial(orgId, planKey) {
  const plan = getPlan(planKey);
  if (plan.key === 'free') throw new Error('Free does not need a trial.');
  const { rows } = await pool.query('SELECT has_used_trial FROM organizations WHERE id = $1', [orgId]);
  if (!rows[0] || rows[0].has_used_trial) throw new Error('This organization has already used its trial.');

  const trialEndsAt = new Date(Date.now() + TRIAL_DAYS * 24 * 60 * 60 * 1000);
  await pool.query(
    `UPDATE organizations
     SET plan_key = $2, subscription_status = 'trial', trial_ends_at = $3,
         has_used_trial = TRUE, trial_reminder_sent_at = NULL
     WHERE id = $1`,
    [orgId, plan.key, trialEndsAt]
  );
  await notifyOrgAdmins(orgId, `Your ${TRIAL_DAYS}-day trial of ${plan.name} has started.`, '/billing');
  return trialEndsAt;
}

// --- Route-gating middleware -----------------------------------------
// Requires requireOrg to have already run (needs req.orgId / req.plan).
// req.plan is attached once per request in server.js's org-context
// middleware, so these never need an extra query.

function requireFeature(featureKey) {
  return (req, res, next) => {
    if (req.plan && req.plan[featureKey]) return next();
    res.redirect(`/billing/upgrade?reason=${encodeURIComponent(featureKey)}`);
  };
}

// For JSON/fetch-based routes, where redirecting to an HTML page isn't
// useful -- the client needs a status it can branch on.
function requireFeatureApi(featureKey) {
  return (req, res, next) => {
    if (req.plan && req.plan[featureKey]) return next();
    res.status(402).json({ error: 'This feature needs a paid plan.', upgradeUrl: `/billing/upgrade?reason=${encodeURIComponent(featureKey)}` });
  };
}

async function requireBoardLimit(req, res, next) {
  if (!req.plan || req.plan.boardLimit === null || req.plan.boardLimit === undefined) return next();
  const usage = await getOrgUsage(req.orgId);
  if (usage.boards < req.plan.boardLimit) return next();
  res.redirect('/billing/upgrade?reason=boardLimit');
}

async function requireSeatLimit(req, res, next) {
  if (!req.plan || req.plan.seatLimit === null || req.plan.seatLimit === undefined) return next();
  const usage = await getOrgUsage(req.orgId);
  if (usage.seats < req.plan.seatLimit) return next();
  // This route (adding a member) is a traditional form POST, not fetch --
  // see routes/users.js -- so a redirect is the right response here,
  // unlike the *Api variants above.
  res.redirect('/billing/upgrade?reason=seatLimit');
}

async function requireAttachmentRoom(req, res, next) {
  if (!req.plan) return next();
  const usage = await getOrgUsage(req.orgId);
  const limitBytes = req.plan.attachmentLimitMb * 1024 * 1024;
  // Multer has already buffered the incoming files into req.files by the
  // time this runs (it's placed after the multer middleware on the
  // route), so their combined size is known without a DB round trip.
  const incomingBytes = (req.files || []).reduce((sum, f) => sum + f.size, 0);
  if (usage.attachmentBytes + incomingBytes <= limitBytes) return next();
  res.status(402).json({ error: 'This would put the organization over its attachment storage limit.', upgradeUrl: '/billing/upgrade?reason=attachmentLimit' });
}

module.exports = {
  PLANS,
  PLAN_ORDER,
  TRIAL_DAYS,
  getPlan,
  planList,
  getOrgUsage,
  getLockedBoardIds,
  isBoardLocked,
  notifyOrgAdmins,
  applyChargeSuccess,
  syncOrgPlan,
  startTrial,
  requireFeature,
  requireFeatureApi,
  requireBoardLimit,
  requireSeatLimit,
  requireAttachmentRoom
};
