const pool = require('../db/pool');
const { notify } = require('./notify');

// Single source of truth for every plan's limits, features, and price.
// Paystack plan codes come from env vars (created manually in the Paystack
// dashboard -- see .env.example) rather than being generated by the app,
// so there's nothing here that needs a live API call to define.
const PLANS = {
  free: {
    key: 'free', name: 'Free', tagline: 'Try it out',
    seatLimit: 3, boardLimit: 1, attachmentLimitMb: 0,
    hasMap: false, hasExport: false, hasOrgTags: false, hasMultiAdmin: false,
    priceMonthly: 0, priceAnnual: 0,
    paystackPlanCode: { monthly: null, annual: null }
  },
  individual: {
    key: 'individual', name: 'Individual', tagline: 'One person, self-pay',
    seatLimit: 1, boardLimit: null, attachmentLimitMb: 250,
    hasMap: true, hasExport: true, hasOrgTags: false, hasMultiAdmin: false,
    priceMonthly: 5, priceAnnual: 48,
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PLAN_INDIVIDUAL_MONTHLY,
      annual: process.env.PAYSTACK_PLAN_INDIVIDUAL_ANNUAL
    }
  },
  team_starter: {
    key: 'team_starter', name: 'Team Starter', tagline: 'Up to 5 seats',
    seatLimit: 5, boardLimit: null, attachmentLimitMb: 1024 + 5 * 200,
    hasMap: true, hasExport: true, hasOrgTags: true, hasMultiAdmin: false,
    priceMonthly: 20, priceAnnual: 190,
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PLAN_TEAM_STARTER_MONTHLY,
      annual: process.env.PAYSTACK_PLAN_TEAM_STARTER_ANNUAL
    }
  },
  team: {
    key: 'team', name: 'Team', tagline: 'Up to 12 seats',
    seatLimit: 12, boardLimit: null, attachmentLimitMb: 1024 + 12 * 200,
    hasMap: true, hasExport: true, hasOrgTags: true, hasMultiAdmin: false,
    priceMonthly: 48, priceAnnual: 460,
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PLAN_TEAM_MONTHLY,
      annual: process.env.PAYSTACK_PLAN_TEAM_ANNUAL
    }
  },
  team_growth: {
    key: 'team_growth', name: 'Team Growth', tagline: 'Up to 25 seats',
    seatLimit: 25, boardLimit: null, attachmentLimitMb: 1024 + 25 * 500,
    hasMap: true, hasExport: true, hasOrgTags: true, hasMultiAdmin: true,
    priceMonthly: 90, priceAnnual: 850,
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PLAN_TEAM_GROWTH_MONTHLY,
      annual: process.env.PAYSTACK_PLAN_TEAM_GROWTH_ANNUAL
    }
  },
  team_business: {
    key: 'team_business', name: 'Team Business', tagline: 'Up to 50 seats',
    seatLimit: 50, boardLimit: null, attachmentLimitMb: 1024 + 50 * 500,
    hasMap: true, hasExport: true, hasOrgTags: true, hasMultiAdmin: true,
    priceMonthly: 160, priceAnnual: 1500,
    paystackPlanCode: {
      monthly: process.env.PAYSTACK_PLAN_TEAM_BUSINESS_MONTHLY,
      annual: process.env.PAYSTACK_PLAN_TEAM_BUSINESS_ANNUAL
    }
  }
};

const PLAN_ORDER = ['free', 'individual', 'team_starter', 'team', 'team_growth', 'team_business'];

function getPlan(key) {
  return PLANS[key] || PLANS.free;
}

function planList() {
  return PLAN_ORDER.map((k) => PLANS[k]);
}

// How much of an org's limits are currently used. Board/seat counts are
// cheap COUNTs; attachments sum the existing size_bytes column rather than
// reading BYTEA content, so this stays fast even with large files stored.
async function getOrgUsage(orgId) {
  const { rows: boardRows } = await pool.query('SELECT COUNT(*)::int AS count FROM boards WHERE org_id = $1', [orgId]);
  const { rows: seatRows } = await pool.query('SELECT COUNT(*)::int AS count FROM org_members WHERE org_id = $1', [orgId]);
  const { rows: attRows } = await pool.query(
    `SELECT COALESCE(SUM(ca.size_bytes), 0)::bigint AS bytes
     FROM card_attachments ca
     JOIN cards c ON c.id = ca.card_id
     JOIN lists l ON l.id = c.list_id
     JOIN boards b ON b.id = l.board_id
     WHERE b.org_id = $1`,
    [orgId]
  );
  const attachmentBytes = Number(attRows[0].bytes);
  return {
    boards: boardRows[0].count,
    seats: seatRows[0].count,
    attachmentBytes,
    attachmentMb: Math.round((attachmentBytes / (1024 * 1024)) * 10) / 10
  };
}

// Which board IDs are over the org's current board limit and should be
// treated as read-only. Oldest boards (by creation date) stay active;
// the newest ones beyond the limit get locked -- predictable and doesn't
// require picking anything for the admin.
async function getLockedBoardIds(orgId, boardLimit) {
  if (boardLimit === null || boardLimit === undefined) return new Set();
  const { rows } = await pool.query(
    'SELECT id FROM boards WHERE org_id = $1 ORDER BY created_at ASC OFFSET $2',
    [orgId, boardLimit]
  );
  return new Set(rows.map((r) => r.id));
}

async function isBoardLocked(orgId, boardId, boardLimit) {
  if (boardLimit === null || boardLimit === undefined) return false;
  const locked = await getLockedBoardIds(orgId, boardLimit);
  return locked.has(Number(boardId));
}

async function notifyOrgAdmins(orgId, message, link) {
  const { rows } = await pool.query(`SELECT user_id FROM org_members WHERE org_id = $1 AND role = 'admin'`, [orgId]);
  await Promise.all(rows.map((r) => notify(r.user_id, orgId, message, link)));
}

// Called once per request (from the org-context middleware in server.js)
// with the org row already loaded. If a canceled subscription's paid
// period has ended, or a payment-failure grace period has expired, this
// downgrades the org to Free right here -- no cron job needed, since every
// authenticated page load passes through here anyway. Returns the
// (possibly updated) org fields so the rest of the request uses correct,
// current values instead of a stale plan.
async function syncOrgPlan(org) {
  if (!org || org.plan_key === 'free') return org;
  const now = new Date();
  const periodEnded = org.current_period_end && new Date(org.current_period_end) < now;
  const graceEnded = org.grace_period_ends_at && new Date(org.grace_period_ends_at) < now;

  const shouldDowngrade =
    (org.subscription_status === 'canceled' && periodEnded) ||
    (org.subscription_status === 'grace' && graceEnded);

  if (!shouldDowngrade) return org;

  await pool.query(
    `UPDATE organizations
     SET plan_key = 'free', billing_cycle = NULL, subscription_status = 'none',
         current_period_end = NULL, grace_period_ends_at = NULL
     WHERE id = $1`,
    [org.id]
  );
  await notifyOrgAdmins(
    org.id,
    'Your subscription has ended and this organization has moved to the Free plan. Boards and members beyond the Free plan\'s limits are now read-only until you upgrade.',
    '/billing'
  );
  return {
    ...org,
    plan_key: 'free',
    billing_cycle: null,
    subscription_status: 'none',
    current_period_end: null,
    grace_period_ends_at: null
  };
}

// --- Route-gating middleware -----------------------------------------
// Requires requireOrg to have already run (needs req.orgId / req.plan).
// req.plan is attached once per request in server.js's org-context
// middleware, so these never need an extra query.

function requireFeature(featureKey) {
  return (req, res, next) => {
    if (req.plan && req.plan[featureKey]) return next();
    res.redirect(`/billing/upgrade?reason=${encodeURIComponent(featureKey)}`);
  };
}

// For JSON/fetch-based routes, where redirecting to an HTML page isn't
// useful -- the client needs a status it can branch on.
function requireFeatureApi(featureKey) {
  return (req, res, next) => {
    if (req.plan && req.plan[featureKey]) return next();
    res.status(402).json({ error: 'This feature needs a paid plan.', upgradeUrl: `/billing/upgrade?reason=${encodeURIComponent(featureKey)}` });
  };
}

async function requireBoardLimit(req, res, next) {
  if (!req.plan || req.plan.boardLimit === null || req.plan.boardLimit === undefined) return next();
  const usage = await getOrgUsage(req.orgId);
  if (usage.boards < req.plan.boardLimit) return next();
  res.redirect('/billing/upgrade?reason=boardLimit');
}

async function requireSeatLimit(req, res, next) {
  if (!req.plan || req.plan.seatLimit === null || req.plan.seatLimit === undefined) return next();
  const usage = await getOrgUsage(req.orgId);
  if (usage.seats < req.plan.seatLimit) return next();
  // This route (adding a member) is a traditional form POST, not fetch --
  // see routes/users.js -- so a redirect is the right response here,
  // unlike the *Api variants above.
  res.redirect('/billing/upgrade?reason=seatLimit');
}

async function requireAttachmentRoom(req, res, next) {
  if (!req.plan) return next();
  const usage = await getOrgUsage(req.orgId);
  const limitBytes = req.plan.attachmentLimitMb * 1024 * 1024;
  // Multer has already buffered the incoming files into req.files by the
  // time this runs (it's placed after the multer middleware on the
  // route), so their combined size is known without a DB round trip.
  const incomingBytes = (req.files || []).reduce((sum, f) => sum + f.size, 0);
  if (usage.attachmentBytes + incomingBytes <= limitBytes) return next();
  res.status(402).json({ error: 'This would put the organization over its attachment storage limit.', upgradeUrl: '/billing/upgrade?reason=attachmentLimit' });
}

module.exports = {
  PLANS,
  PLAN_ORDER,
  getPlan,
  planList,
  getOrgUsage,
  getLockedBoardIds,
  isBoardLocked,
  notifyOrgAdmins,
  syncOrgPlan,
  requireFeature,
  requireFeatureApi,
  requireBoardLimit,
  requireSeatLimit,
  requireAttachmentRoom
};
